com.ssafy:
  db.url.host: host.docker.internal
  backeth.base_url: http://host.docker.internal:8082/api
  save_dummy_job: false

spring.output.ansi.enabled: never

logging.file.name: logs/backend.log

# com.ssafy.kakao.redirect_uri: https://j7b106.p.ssafy.io/loginresult
com.ssafy.kakao.redirect_uri: http://localhost:3000/loginresult

# env from production runtime
#
#   spring.datasource.username
#   spring.datasource.password
#   jwt.secret
#   com.ssafy.kakao.client_id
