spring.output.ansi.enabled: never
logging.file.name: logs/backend.log

# env from production runtime
#
#   spring.datasource.url
#   spring.datasource.username
#   spring.datasource.password
#   jwt.secret
#   com.ssafy.kakao.client_id
#   com.ssafy.kakao.redirect_uri
